name: Build Android TWA (bubblewrap)
on:
  push:
    branches: [ main ]
jobs:
  build-twa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Install bubblewrap
        run: |
          npm install -g @bubblewrap/cli
      - name: Build TWA
        env:
          # Provide repository URL (must be HTTPS and reachable)
          REPO_URL: ${{ secrets.TWA_REPO_URL }}
        run: |
          # This assumes azan-watch is hosted publicly and manifest is available.
          # Customize package id and other fields as needed.
          npx bubblewrap init --manifest=$REPO_URL/manifest.json --packageId=com.example.azanwatch --path=twa-output --manifestVersionCode=1 || true
          cd twa-output || exit 0
          npx bubblewrap build --output=output || true
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: twa-output
          path: twa-output/output || twa-output
