name: Flutter Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2.10.0
      - run: |
          flutter create --platforms android iqra_app
          cd iqra_app
          flutter build apk --release
      - uses: actions/upload-artifact@v4
        with:
          name: apk
          path: iqra_app/build/app/outputs/flutter-apk/app-release.apk
