name: Build TWA APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install Bubblewrap and dependencies
      run: |
        npm install -g @bubblewrap/cli
        sudo apt-get update
        sudo apt-get install -y expect
        
    - name: Initialize TWA project with auto-answers
      run: |
        expect << EOF
        set timeout 30
        spawn npx @bubblewrap/cli init --manifest=https://YOUR-DOMAIN.com/manifest.json --directory=twa-project
        expect "Do you want Bubblewrap to install the JDK"
        send "y\r"
        expect eof
        EOF
        
    - name: Build APK
      run: |
        cd twa-project
        npx @bubblewrap/cli build
