name: Generate TWA Assets
on: workflow_dispatch

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create TWA config
      run: |
        # Create assetlinks.json for TWA
        cat > assetlinks.json << 'EOF'
        [{
          "relation": ["delegate_permission/common.handle_all_urls"],
          "target": {
            "namespace": "web",
            "site": "https://YOUR-DOMAIN.com"
          }
        }]
        EOF
        
        # Create basic TWA documentation
        cat > TWA_INSTRUCTIONS.md << 'EOF'
        # TWA Build Instructions
        
        1. Host your PWA on HTTPS (Netlify, Vercel, GitHub Pages)
        2. Update manifest.json with your domain
        3. Use Android Studio with Bubblewrap CLI
        4. Build signed APK for Play Store
        
        Your files are ready for TWA conversion!
        EOF
        
    - name: Upload TWA assets
      uses: actions/upload-artifact@v4
      with:
        name: twa-assets
        path: |
          assetlinks.json
          TWA_INSTRUCTIONS.md
          manifest.json
          icon-192.png
          icon-512.png
