name: Build TWA APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Setup Java JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Install Bubblewrap
      run: |
        npm install -g @bubblewrap/cli
        
    - name: Check Java installation
      run: |
        java -version
        javac -version
        
    - name: Initialize TWA project
      run: |
        npx @bubblewrap/cli init --manifest=https://YOUR-DOMAIN.com/manifest.json --directory=twa-project
        
    - name: Build APK
      run: |
        cd twa-project
        npx @bubblewrap/cli build
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: azan-watch-twa
        path: twa-project/app/build/outputs/apk/release/*.apk
